/**:
  ros__parameters:
    plugin_denylist: ['actuator_control', 'ftp', 'safety_area', 'hil', 'altitude', 'debug_value', 'image_pub', 'px4flow', 'vibration', 'vision_speed_estimate', 'wheel_odometry']
# common
#    - actuator_control
#    - ftp
#    - safety_area
#    - hil
# extras
#    - altitude
#    - debug_value
#    - image_pub
#    - px4flow
#    - vibration
#    - vision_speed_estimate
#    - wheel_odometry
#    plugin_allowlist: []
#- 'sys_*'
