# Common configuration for APM2 autopilot
#
# node:
mavros:
  ros__parameters:
    startup_px4_usb_quirk: false

# --- mavros plugins (alphabetical order) ---

# 3dr_radio
tdr_radio:
  ros__parameters:
    low_rssi: 40  # raw rssi lower level for diagnostics

# local_position
local_position:
  ros__parameters:
    frame_id: "map"
    tf:
      send: false
      frame_id: "map"
      child_frame_id: "base_link"
      send_fcu: false

# param
# None, used for FCU params

# rc_io
# None

# setpoint_accel
setpoint_accel:
  ros__parameters:
    send_force: false

# setpoint_attitude
setpoint_attitude:
  ros__parameters:
    reverse_thrust: false     # allow reversed thrust
    use_quaternion: false     # enable PoseStamped topic subscriber
    tf:
      listen: false           # enable tf listener (disable topic subscribers)
      frame_id: "map"
      child_frame_id: "target_attitude"
      rate_limit: 50.0

# setpoint_raw
setpoint_raw:
  ros__parameters:
    thrust_scaling: 1.0       # specify thrust scaling (normalized, 0 to 1) for thrust (like PX4)

# setpoint_position
setpoint_position:
  ros__parameters:
    tf:
      listen: false           # enable tf listener (disable topic subscribers)
      frame_id: "map"
      child_frame_id: "target_position"
      rate_limit: 50.0
    mav_frame: LOCAL_NED

# setpoint_velocity
setpoint_velocity:
  ros__parameters:
    mav_frame: LOCAL_NED

# vfr_hud
# None

# waypoint
mission:
  ros__parameters:
    pull_after_gcs: true  # update mission if gcs updates
    use_mission_item_int: true # use the MISSION_ITEM_INT message instead of MISSION_ITEM
                             # for uploading waypoints to FCU
                             
# --- mavros extras plugins (same order) ---

# adsb
# None

# debug_value
# None

# distance_sensor
## Currently available orientations:
#    Check http://wiki.ros.org/mavros/Enumerations
##
distance_sensor:
  ros__parameters:
    rangefinder_pub:
      id: 0
      frame_id: "lidar"
      #orientation: PITCH_270 # sended by FCU
      field_of_view: 0.0  # XXX TODO
      send_tf: false
      sensor_position: {x:  0.0, y:  0.0, z:  -0.1}
    rangefinder_sub:
      subscriber: true
      id: 1
      orientation: PITCH_270  # only that orientation are supported by APM 3.4+

# fake_gps
fake_gps:
  ros__parameters:
  # select data source
    use_mocap: true         # ~mocap/pose
    mocap_transform: false  # ~mocap/tf instead of pose
    mocap_withcovariance: false  # ~mocap/pose uses PoseWithCovarianceStamped Message
    use_vision: false       # ~vision (pose)
    use_hil_gps: true
    gps_id: 4
  # origin (default: Zürich)
    geo_origin:
      lat: 47.3667          # latitude [degrees]
      lon: 8.5500           # longitude [degrees]
      alt: 408.0            # altitude (height over the WGS-84 ellipsoid) [meters]
    eph: 2.0
    epv: 2.0
    horiz_accuracy: 0.5
    vert_accuracy: 0.5
    speed_accuracy: 0.0
    satellites_visible: 6   # virtual number of visible satellites
    fix_type: 3             # type of GPS fix (default: 3D)
    tf:
      listen: false
      send: false           # send TF?
      frame_id: "map"       # TF frame_id
      child_frame_id: "fix" # TF child_frame_id
      rate_limit: 10.0      # TF rate
    gps_rate: 5.0           # GPS data publishing rate

# landing_target
landing_target:
  ros__parameters:
    listen_lt: false
    mav_frame: "LOCAL_NED"
    land_target_type: "VISION_FIDUCIAL"
    image:
      width: 640            # [pixels]
      height: 480
    camera:
      fov_x: 2.0071286398   # default: 115 [degrees]
      fov_y: 2.0071286398
    tf:
      send: true
      listen: false
      frame_id: "landing_target"
      child_frame_id: "camera_center"
      rate_limit: 10.0
    target_size: {x:  0.3, y:  0.3}

# mocap_pose_estimate
mocap:
  ros__parameters:
  # select mocap source
    use_tf: false   # ~mocap/tf
    use_pose: true  # ~mocap/pose

# odom
odometry:
  ros__parameters:
    frame_tf:
      desired_frame: "ned"
    estimator_type: 3 # check enum MAV_ESTIMATOR_TYPE in <https://mavlink.io/en/messages/common.html>

# vision_pose_estimate
vision_pose:
  ros__parameters:
    tf:
      listen: false           # enable tf listener (disable topic subscribers)
      frame_id: "map"
      child_frame_id: "vision_estimate"
      rate_limit: 10.0
