[program:xterm1]
command=bash -c 'sleep 10; xterm -T "MAVROS" -geometry "90x24+0+0" -e "ros2 launch mavros descert_adj.launch.py fcu_url:=udp://127.0.0.1:14550@ > /tmp/mavros.log 2>&1"'
#command=bash -c '/app-novnc/scripts/start_mavros.sh'
autostart=true
autorestart=false
priority=350

[program:xterm2]
command=xterm -T "Vehicle Sim" -geometry "90x30+0+0" -e "sim_vehicle.py -N -v ArduCopter --console --map --out=udp:127.0.0.1:14550 --out=udp:127.0.0.1:14551 --out=udp:127.0.0.1:14560 --out=udp:127.0.0.1:14570 > /tmp/sim_vehicle.log 2>&1"
#command=bash -c '/app-novnc/scripts/start_vehicle_sim.sh'
autostart=true
autorestart=false
priority=350

[program:xterm3]
command=bash -c 'sleep 12; xterm -T "Radler Function" -geometry "90x12+0+0" -e "~/ros2_ws/install/afs/bin/afs_function"'
autostart=true
autorestart=true
priority=360

[program:xterm4]
command=bash -c 'sleep 12; xterm -T "Radler Gateway" -geometry "90x22+0+180" -e "~/ros2_ws/install/afs/bin/afs_gateway"'
autostart=true
autorestart=true
priority=360

# [program:xterm5]
# command=xterm -T "MAVLink Bridge" -geometry "90x10+0+500" -e "/home/ardupilot/start_bridge.sh"
# autostart=true
# autorestart=false
# priority=350

# [program:xterm5]
# command=xterm -T "Blank Display" -geometry "90x24+0+0" -e "cat /dev/null; sleep infinity"
# autostart=true
# autorestart=false
# priority=340

# For Debugging only
# [program:xterm5]
# command=bash -c 'sleep 5; xterm -T "Debug" -geometry "240x200+0+0" -e "source $ROS2_PREFIX/$ROS2_DISTRO/setup.bash && source $ROS2_WS/install/local_setup.bash && rqt_graph"
# autostart=true
# autorestart=false
# priority=370