[program:xterm1]
command=xterm -T "MAVROS" -geometry "120x40+500+0" -e ros2 launch mavros apm.launch.py
autostart=true
autorestart=false
priority=350

[program:xterm2]
command=bash -c 'sleep 2; xterm -T "Vehicle Sim" -geometry "80x40+0+0" -e "sim_vehicle.py -N -v ArduCopter --console --map --out=udp:127.0.0.1:14550 --mavproxy-args=\"--out=udp:127.0.0.1:14551\""'
autostart=true
autorestart=false
priority=350

[program:xterm3]
command=xterm -T "Radler Gateway" -geometry "40x24+0+550" -e ~/ros2_ws/install/afs/bin/afs_gateway
autostart=true
autorestart=true
priority=350

[program:xterm4]
command=xterm -T "Radler Function" -geometry "30x24+250+550" -e ~/ros2_ws/install/afs/bin/afs_function
autostart=true
autorestart=true
priority=350

