[program:xterm1]
command=xterm -T "MAVROS" -geometry "90x24+0+0" -e ros2 launch mavros descert_adj.launch.py fcu_url:="udp://127.0.0.1:14550@"
autostart=true
autorestart=false
priority=350

[program:xterm2]
command=bash -c 'sleep 2; xterm -T "Vehicle Sim" -geometry "90x24+0+450" -e "sim_vehicle.py -N -v ArduCopter --console --map --out=udp:127.0.0.1:14550 --out=udp:127.0.0.1:14551"'
autostart=true
autorestart=false
priority=350

[program:xterm3]
command=bash -c 'sleep 12; xterm -T "Radler Function" -geometry "90x12+0+0" -e "~/ros2_ws/install/afs/bin/afs_function"'
autostart=true
autorestart=true
priority=360

[program:xterm4]
command=bash -c 'sleep 12; xterm -T "Radler Gateway" -geometry "90x20+0+180" -e "~/ros2_ws/install/afs/bin/afs_gateway"'
autostart=true
autorestart=true
priority=360

# For Debugging only
# [program:xterm5]
# command=bash -c 'sleep 5; xterm -T "Debug" -geometry "240x200+0+0" -e "source $ROS2_PREFIX/$ROS2_DISTRO/setup.bash && source $ROS2_WS/install/local_setup.bash && rqt_graph"
# autostart=true
# autorestart=false
# priority=370