#MM: work in progress - expect "command" to disappear as ardupilot_entrypoint.sh includes multiple windows
services:
  novnc-ardupilot:
    image: radler/ardupilot:novnc
    ports:
      - "8090:8090"



